sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t daviddaming/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true daviddaming/docker-react npm run test

deploye:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-247670168413"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id: $AWS_SECRET_KEY
